---
title: "Práctica 2. Mapeo de secuencias cortas"
lang: es
date: today
execute: 
  output: true
  error: true
engine: knitr
bibliography: ../../doc/references.bib
language:
   title-block-published: "Última actualización:"
   section-title-references: "Bibliografía"
format:
   html:
      embed-resources: true
---


# Objetivos
1. Control de calidad de lecturas cortas.
2. Mapeo de lecturas cortas a un genoma de referencia.
3. Identificación de variantes.

# Datos
A continuación descargamos un par de archivos FASTQ de la base de datos
[ENA](https://www.ebi.ac.uk/ena/browser/home). Han sido seleccionados porque
su tamaño (comprimidos) no supera los 100 MB. Son secuencias de la cepa Tsu4-125
de *Bradyrhizobium japonicum* (bacteria simbionte de la planta de soja). Proceden
de la [Universidad de Tohoku](https://www.tohoku.ac.jp/en/) y forman parte de un
[proyecto](https://www.ebi.ac.uk/ena/browser/view/PRJDB3261) en el que se
secuenciaron 16 cepas más de *Bradyrhizobium*.

```{bash}
if [ ! -e DRR025089_1.fastq.gz ]; then
   # Con la opción "-o /dev/null" nos deshacemos de los mensajes.
   wget -o /dev/null \
        ftp://ftp.sra.ebi.ac.uk/vol1/fastq/DRR025/DRR025089/DRR025089_1.fastq.gz
fi
if [ ! -e DRR025089_2.fastq.gz ]; then
   wget -o /dev/null \
        ftp://ftp.sra.ebi.ac.uk/vol1/fastq/DRR025/DRR025089/DRR025089_2.fastq.gz
fi
```

:::{.callout-note icon=false}
## Desafío
**Una vez descargados los archivos FASTQ, échales un vistazo desde la línea de órdenes. Puedes hacerlo con `zless`, una versión de `less` capaz de mostrar archivos comprimidos, o bien descomprimiendo los archvios con `gunzip`. Para no ocupar espacio de disco innecesariamente, puedes usar**
`gunzip -c DRR025089_1.fastq.gz | less -S`, **que envía el contenido del archivo a la salida estándar (no a un archivo nuevo), de donde `less -S` lo lee, sin modificar nada en la carpeta. ¿Sabrías contar el número de líneas de cada archivo?**

Se puede contar el numero de lineas de cada archivo con el comando gunzip -c nombre I wc -l.
Eese comando te da el numero de lineas. Tenemos que comprobar que los dos archivos tienen el mismo numero de lineas, sino habria algun error, da que hay 1646728 en los dos archivos.
:::

Necesitaremos también el genoma de referencia de `Bradyrhizobium japonicum`.
Usaremos el de la cepa ACCC 15027 (hay otros).

```{bash}
# Con la opción "-o /dev/null" nos deshacemos de los mensajes,
# y con "-O referencia.fa" escogemos un nombre adecuado para el archivo.
if [ ! -e referencia.fa ]; then
   wget -o /dev/null -O referencia.fa \
        https://www.ebi.ac.uk/ena/browser/api/fasta/GCA_042137995.2 
fi
```

:::{.callout-note icon=false}
## Preguntas
- **¿Crees que deberíamos guardar los archivos descargados en `../../data`?**
Debemos guardarlos en data, esa carpeta git la ignora
- **¿Cómo podrías guardar los mensajes de `wget` en un archivo?**
- **¿De cuántas secuencias diferentes se compone este genoma de referencia?**
Vemos el archivo de referencia en el terminal con less referencia.fa, ahora hay que contar el numero de lineas, con less -c referencia.fa  | wc -l, el nº de secuencias es 167052.
:::

# Control de calidad

```{bash}
if [ ! -e fastp.html ]; then
   # Si "fastp" está en la carpeta actual y  no en el PATH, escribe "./fastp"
   # en lugar de "fastp".
   ~/bin/fastp -i ../../data/DRR025089_1.fastq.gz \
         -o DRR025089_1_clean.fastq \
         -I ../DRR025089_2.fastq.gz \
         -O DRR025089_2_clean.fastq \
         --merge \
         --merged_out DRR025089_m_clean.fastq
fi
```

:::{.callout-note icon=false}
## Ejercicios
1. Revisa la ayuda del programa ejecutando `fastp -h`, y asegúrate de entender
   al menos las opciones que hemos usado.
2. Revisa el informe generado por `fastp` en el archivo `fastp.html` y redacta un
   pequeño resumen de las principales conclusiones que sacas.
3. Descarga un segundo conjunto de archivos FASTQ de la misma especie y repite
   el análisis de calidad con ellos. Puedes ver algunas opciones en
   [este enlace](https://www.ebi.ac.uk/ena/browser/advanced-search?result=read_run&query=study_accession%3D%22PRJDB3261%22&fields=run_accession%2Cexperiment_title%2Cstudy_accession%2Cfastq_bytes%2Cfastq_ftp%2Cscientific_name%2Cfirst_public&excludeAccessionType=run&excludeAccessions=DRR025089).
   Es mejor no descargar archivos demasiado grandes.
:::

# Mapeo
El objetivo de esta sección es alinear las lecturas cortas al genoma de
referencia, mediante el programa `bwa`. El archivo final será un archivo BAM
*ordenado*. Para obtener ese archivo es necesario generar algunos archivos
auxiliares: primero, el índice del genoma de referencia, después los alineamientos
en formato SAM (no comprimidos) y finalmente un archivo BAM, que es la versión
comprimida del SAM (todavía no ordenado). La jerarquía de condiciones de ejecución
siguiente permitirá borrar los archivos auxiliares, para ahorrar espacio, y no tener
que generarlos de nuevo cada vez que compilemos este documento si el archivo final
ya está presente en la carpeta de trabajo.

```{bash}
if [ ! -e DRR025089.bam ]; then
   if [ ! -e DRR025089_unsorted.bam ]; then
      if [ ! -e DRR025089.sam ]; then
         if [ ! -e referencia.fa.bwt ]; then
            bwa index referencia.fa
         fi
         bwa mem -M -R '@RG\tID:DRR025089\tSM:SAMD00022947' \
                 -o DRR025089.sam \
                 referencia.fa \
                 DRR025089_1_clean.fastq \
                 DRR025089_2_clean.fastq \
         1> bwa.log 2> bwa.err
      fi
      samtools view -b -o DRR025089_unsorted.bam DRR025089.sam
    fi
    samtools sort -o DRR025089.bam DRR025089_unsorted.bam
    samtools index DRR025089.bam
fi
```

:::{.callout-note icon=false}
## Desafíos
1. Entre las órdenes anteriores, añade la descarga del genoma de referencia
   en el lugar adecuado y bajo la condición adecuada para que pueda borrarse
   una vez se haya generado el alineamiento.
2. En un bloque de órdenes nuevo, alinea también los pares de lecturas cortas
   que `fastp` había combinado (`DR025089_m_clean.fastq`).
3. Lee la lista de funciones que te ofrece `samtools` al ejecutarlo sin ningún
   argumento. ¿Qué función usarías para combinar dos archvivos BAM en uno?
3. ¿Cuánto espacio de disco ocupan los archivos FASTQ, el genoma de referencia y
   su índice y el archivo SAM?
4. Podíamos haber ahorrado algún paso aprovechando las *tuberías* de BASH:

```
bwa mem -M -R '@RG\tID:DRR025089\tSM:SAMD00022947' \
        referencia.fa DRR025089_1_clean.fastq DRR025089_2_clean.fastq | \
samtools view -u - | \
samtools sort - > DRR025089.bam
```

  Este estilo tiene también la ventaja de ser más rápido. ¿Crees que hay algún
  inconveniente al usar las tuberías?
:::

Antes de proseguir, es importante comprobar el resultado del paso anterior.
Podemos extraer algunas estadísticas del archivo BAM así:

```{bash}
if [ ! -e DRR025089.stats.txt ]; then
   samtools stats DRR025089.bam > DRR025089.stats.txt
fi

# Extraemos la sección sobre profundidad de cobertura
if [ ! -e stat.$i.txt ]; then
   grep ^COV DRR025089.stats.txt | cut -f 2- > COV.txt
fi
```

Ahora podemos importar los datos de cobertura a una sesión de R y representarlos
gráficamente:

```{r}
COV <- read.table('COV.txt',
                  col.names = c('intervalo', 'cobertura', 'bases'))
plot(COV$cobertura, COV$bases, type = 'l')
```

:::{.callout-note icon=false}
## Desafíos
1. La distribución de cobertura tiene una cola larga. ¿Puedes centrar la
   representación gráfica entre 0 y 20? Pista: usa la opción `xlim` de `plot()`.
2. ¿Qué otras estadísticas crees que vale la pena revisar?
3. El genoma de referencia incluye dos plásmidos. ¿La cepa secuenciada los tiene?
4. Visualiza los alineamientos en el terminal con la orden siguiente:
```
samtools tview DRR025089.bam referencia.fa
```
:::

# Identificación de variantes

```{bash}
if [ ! -e DRR025089.vcf ]; then
   freebayes -p 1 -f referencia.fa DRR025089.bam > DRR025089.vcf
fi
```

